"""Simulated organism lifecycle engine."""
from __future__ import annotations
import shutil
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "digestive-engine"))
from analyzer import digest
from codefarm_common import ROOT, load_state, log_event, read_json, save_state, utc_now

def write_solution(output_file: Path) -> None:
    output_file.write_text('''"""Generated by a CodeFarm organism."""
from __future__ import annotations

import json
from typing import Any


def safe_json_loads(text: str, default: Any = None) -> Any:
    """Parse JSON text and return default when decoding fails."""
    try:
        return json.loads(text)
    except (TypeError, json.JSONDecodeError):
        return default
''', encoding="utf-8")

def run_cycle(organism_id: str) -> dict:
    state = load_state()
    organism = state.setdefault("organisms", {}).setdefault(organism_id, {})
    org_root = ROOT / "organisms" / organism_id
    output_dir = org_root / "output"
    stomach = org_root / "stomach"
    output_dir.mkdir(parents=True, exist_ok=True)
    stomach.mkdir(parents=True, exist_ok=True)
    pending = sorted((ROOT / "tasks" / "pending").glob("*.json"))
    if not pending:
        log_event(f"HUNGER organism={organism_id} no_tasks_available")
        organism["status"] = "starving"
        save_state(state)
        return organism
    task_path = pending[0]
    task = read_json(task_path, {})
    output_file = output_dir / f"{task.get('id', 'task')}.py"
    write_solution(output_file)
    result = digest(output_file, task_path)
    calories = int(result["nutrients"]["nutrient_value"])
    organism["energy"] = int(organism.get("energy", 100)) - int(organism.get("energy_decay_per_cycle", 8)) + calories
    organism["status"] = "thriving" if organism["energy"] >= organism.get("starvation_threshold", 120) else "weak"
    organism["last_task"] = task.get("id")
    organism["last_output"] = str(output_file)
    organism["last_quality"] = result["nutrients"]["weighted_quality"]
    organism["lifetime_nutrients"] = int(organism.get("lifetime_nutrients", 0)) + calories
    organism["updated_at"] = utc_now()
    organism["consecutive_low_quality_outputs"] = 0 if calories >= int(organism.get("starvation_threshold", 120)) else int(organism.get("consecutive_low_quality_outputs", 0)) + 1
    pool = state.setdefault("nutrient_pool", {})
    pool["available_calories"] = int(pool.get("available_calories", 0)) + calories
    metrics = state.setdefault("metrics", {})
    metrics["lifetime_nutrients"] = int(metrics.get("lifetime_nutrients", 0)) + calories
    metrics.setdefault("quality_history", []).append({"at": utc_now(), "organism": organism_id, "quality": result["nutrients"]["weighted_quality"]})
    state["cycle"] = int(state.get("cycle", 0)) + 1
    save_state(state)
    shutil.move(str(task_path), str(ROOT / "tasks" / "completed" / task_path.name))
    with (org_root / "vitals.log").open("a", encoding="utf-8") as handle:
        handle.write(f"{utc_now()} energy={organism['energy']} calories={calories} status={organism['status']}\n")
    log_event(f"WORK organism={organism_id} task={task.get('id')} calories={calories} energy={organism['energy']}")
    return organism

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("organism_id")
    args = parser.parse_args()
    organism = run_cycle(args.organism_id)
    print(f"{args.organism_id} status={organism.get('status')} energy={organism.get('energy')}")
